# Generated by Django 4.1.3 on 2023-02-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=60)),
                ('vaqt', models.TimeField()),
                ('batafsil', models.TextField()),
                ('holat', models.BooleanField()),
            ],
        ),
    ]
